Team_Project/Team_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from registration.backends.simple.views import RegistrationView

from web import views


class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        print(request.GET.get('next'))
        return '/search/'


urlpatterns = [
    path('', include('web.urls')),
    path('admin/', admin.site.urls),
    path('index/', views.index),
    path('accounts/', include('registration.backends.simple.urls')),
    path('social/', include('social_django.urls', namespace='social'))
]

Team_Project/web/urls.py
from django.urls import path, re_path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('game/', views.game, name='game'),
    re_path(r'^game/(\d+.)$', views.game_info, name='game_info'),
    re_path(r'^category/(\S+.)$', views.category, name='category'),
    path('searchappid/', views.searchappid, name='searchappid'),
    re_path(r'^search/(.+)$', views.result, name='result'),
    path('search/', views.search, name='search'),
    path('like/', views.like, name='like'),
    path('comment/', views.comment, name='comment'),
]

Team_Project/templates/base.html
<!doctype html>
{% load staticfiles %}
{% load web_template_tags %}

<html lang="en">
<head>

    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block head %}
    {% endblock %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

</head>

<style>
    .navbar-user {
        padding: 0;
        margin: 0 auto;
        width: 200px;
        text-align: center;
    }
</style>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- Image and text -->

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <nav class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'web:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button"
                   data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Games
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% block dropdown-menu %}
                        {% get_category_list %}
                    {% endblock %}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'web:game' %}">Something else here</a>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="mailto:2473826h@student.gla.ac.uk?
		subject=Hello&body=FromGCRITIC" id="navbarContact">Contact</a>
            </li>
        </ul>
    </nav>
    <nav class="navbar-logo" style="margin-right: 17%">
        <a class="navbar-brand" href="{% url 'web:index' %}">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRRvYB2Gs3hJ8mOG28GDrHtRs-EdlzHo0nb6CYyWY2RcnofkVE1"
                 width="30" height="30"
                 class="d-inline-block align-top" alt="">
            G-CRITIC
        </a>
    </nav>


    <!-- User Part -->
    {% if user.is_authenticated %}
        <nav class="navbar-user">
          <span class="navbar-text">
            Hello! {{ user.username }}
          </span>
            <a href="{% url 'auth_logout' %}?next={{ request.path }}">
            <span class="navbar-text" id="navbarLogout" style="margin-left: 20px; cursor: pointer" data-toggle="modal"
                  data-target="#logoutModal">
            Logout</span></a>

            <!-- Modal -->
            <div class="modal fade" id="logoutModal" aria-hidden="true" style="margin-left: -50px; z-index: 1060;">
                <div class="modal-dialog modal-sm" role="document">
                    <div class="modal-content" style="text-align: center; width: 400px">
                        <div style="font-size: 40px;">Signing out...</div>
                        <div class="spinner-border text-info" role="status"
                             style="margin-left: 180px; margin-bottom: 20px; margin-top: 10px">
                        </div>
                    </div>
                </div>

            </div>
        </nav>
    {% else %}
        <nav class="navbar-user">
            {#            <a class="navbar-brand" href="{% url 'auth_login' %}" style="margin-left: 100px">#}
            <img src="{% static 'images/user-icon.png' %}" width="30" height="30" data-toggle="modal"
                 data-target="#staticBackdrop" style="cursor: pointer">
            {#            </a>#}
        </nav>

        <!-- Modal -->
        <div class="modal fade" id="staticBackdrop" data-backdrop="static" tabindex="-1" role="dialog"
             aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog" role="document" style="width: 400px">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">Log in</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body" style="text-align: center;">
                        <form method="post" action="{% url 'auth_login' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="inputUsername">Username</label>
                                <input type="text" name="username" id="id_username" class="form-control"
                                       placeholder="Username" required autofocus>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Password</label>
                                <input type="password" name="password" id="id_password" class="form-control"
                                       placeholder="Password" required>
                            </div>
                            <button type="submit" class="btn btn-primary">Log in</button>
                            <input type="hidden" name="next" value="{{ request.path }}"/>
                        </form>
                        <p style="margin-top: 30px">
                            Not registered?
                            <a href="{% url 'registration_register' %}">Register here!</a>
                        </p>
                        <a href="{% url 'social:begin' 'github' %}">Login with GitHub</a><br>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    <div style="float: right">
        <div class="collapse navbar-collapse" id="navbarSearch">

            <input class="form-control mr-sm-2" id="search" name='search' type="text" placeholder="Dota"
                   aria-label="Search" required>
            <button class="btn btn-outline-success my-2 my-sm-0" id="searchButton" type="submit" data-toggle="modal"
                    data-target=".bd-modal-sm" onclick="AjaxSendSearch()">Search
            </button>
        </div>

        <div class="modal fade" id="searchModal" aria-hidden="true" style="margin-left: -50px; z-index: 1060;">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content" style="text-align: center; width: 400px">
                    <div style="font-size: 40px;">Searching...</div>
                    <div class="spinner-border text-info" role="status"
                         style="margin-left: 180px; margin-bottom: 20px; margin-top: 10px">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
            </div>

        </div>

    </div>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bd-example-modal-sm"
            style="margin-left: 10px">APP
    </button>

    <div class="modal fade bd-example-modal-sm" aria-hidden="true" style="z-index: 1050">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3>Search App ID</h3>
                </div>
                <div class="modal-body">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">APP</span>
                        </div>
                        <input id="appid" name="appid" type="text" class="form-control" required>
                        <button class="btn btn-outline-dark" id="searchAppidButton" type="submit"
                                style="margin-left: 10px"
                                onclick="AjaxSendAppid()">Search
                        </button>
                        <span class="invalid-feedback"></span>
                    </div>

                </div>
            </div>
        </div>
    </div>

</nav>


<div class="container-fluid" style="margin-top: 10px; text-align: center;">
    {% block content %}
    {% endblock %}
</div>

<script>
    var searchappid = {% url 'web:searchappid' %};
    var search = {% url 'web:search' %};
    var csrf_token = '{{ csrf_token }}';
</script>
<script src="{% static 'js/ajax.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script>
    $("#search").keydown(function (e) {
        if (e.keyCode === 13) {
            $("#searchButton").click();
        }
    });
    $("#appid").keydown(function (e) {
        if (e.keyCode === 13) {
            $("#searchAppidButton").click();
        }
    });
</script>

</body>
</html>