Team_Project/Team_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from registration.backends.simple.views import RegistrationView

from web import views


class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        print(request.GET.get('next'))
        return '/search/'


urlpatterns = [
    path('', include('web.urls')),
    path('admin/', admin.site.urls),
    path('index/', views.index),
    path('accounts/', include('registration.backends.simple.urls')),
    path('social/', include('social_django.urls', namespace='social'))
]

Team_Project/web/urls.py
from django.urls import path, re_path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('game/', views.game, name='game'),
    re_path(r'^game/(\d+.)$', views.game_info, name='game_info'),
    re_path(r'^category/(\S+.)$', views.category, name='category'),
    path('searchappid/', views.searchappid, name='searchappid'),
    re_path(r'^search/(.+)$', views.result, name='result'),
    path('search/', views.search, name='search'),
    path('like/', views.like, name='like'),
    path('comment/', views.comment, name='comment'),
]

Team_Project/templates/web/categories.html
{% load web_template_tags %}
{% for category in categories %}
    <a class="dropdown-item" href="/category/{{ category.name|spacify }}">{{ category.name }}</a>
{% endfor %}

Team_Project/templates/web/category.html
<!DOCTYPE html>
<style>
    .table-hover{
        cursor: pointer;
    }
</style>

{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    {{ tag }} Games
{% endblock %}

{% block content %}
    <div class="container" style="width: 70%">
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">No</th>
                <th scope="col">Logo</th>
                <th scope="col" width="50%">Name</th>
                <th scope="col" width="10%">Appid</th>
            </tr>
            </thead>
            <tbody>
            {% for i in games %}
                <tr onclick="location.href = '/game/{{ i.0 }}'" style="vertical-align: middle">
                    <th scope="row" style="vertical-align: middle">{{ forloop.counter }}</th>
                    <td><img src="https://steamcdn-a.akamaihd.net/steam/apps/{{ i.0 }}/header.jpg"
                             class="card-img-top" style="width: 250px"></td>
                    <td style="vertical-align: middle">{{ i.1 }}</td>
                    <td style="vertical-align: middle">{{ i.0 }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

Team_Project/templates/web/game_info.html
<!DOCTYPE html>
<style>
    .carousel {
        height: 409px;
        border: 2px solid black;
    }

    .carousel-item {
        height: 405px;
    }

    .carousel-inner img {
        height: 100%;
    }

    .tab-pane {
        max-height: 500px;
        text-align: left;
        margin-top: 5px;
        overflow-y: auto;
    }
</style>


{% extends 'base.html' %}
{% load staticfiles %}
{% load web_template_tags %}

{% block title %}
    {{ game.name }}
{% endblock %}

{% block content %}
    <div class="container">

        <div style="float: left; width: 720px;">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{{ img.0.image }}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{{ img.1.image }}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{{ img.2.image }}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{{ img.3.image }}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{{ img.4.image }}" class="d-block w-100" alt="...">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div style="margin-top: 30px; margin-bottom: 30px">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="description-tab" data-toggle="tab" href="#description" role="tab"
                           aria-controls="description" aria-selected="true">Introduction</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="languages-tab" data-toggle="tab" href="#languages" role="tab"
                           aria-controls="languages" aria-selected="false">Languages</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="requirements-tab" data-toggle="tab" href="#requirements" role="tab"
                           aria-controls="requirements" aria-selected="false">Requirements</a>
                    </li>
                </ul>
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="home-tab">
                        {{ description|safe }}
                    </div>
                    <div class="tab-pane fade" id="languages" role="tabpanel" aria-labelledby="languages-tab">
                        {{ languages | safe }}
                    </div>
                    <div class="tab-pane fade" id="requirements" role="tabpanel" aria-labelledby="requirements-tab">
                        {% for platform in platforms %}
                            {% if platform.requirements != null %}
                                <Strong><p>{{ platform.platform.name }}</p></Strong>
                                {{ platform.requirements.minimum | safe }}
                                <br/>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>


            <div id="user-comments">
                {% for comment in comments %}
                    {% if forloop.counter0 < 5 %}
                        <div class="card" style="margin-top: 20px; text-align: left">
                            <div class="card-header" style="height: 30px; line-height: 0px">
                                {{ comment.user.username }}
                            </div>
                            <div class="card-body">
                                <blockquote class="blockquote mb-0">
                                    <p>{{ comment.comment }}</p>
                                    <footer class="blockquote-footer">Commented at {{ comment.comment_time }} </footer>
                                </blockquote>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>

            {% if user.is_authenticated %}
                {% if isComment %}
                    <div style="margin-top: 50px; text-align: left" class="form-group">
                    <span class="badge badge-pill badge-light"
                          style="font-size: 16px">{{ user.username }}</span>
                    </div>
                    <a type="button" class="btn btn-outline-primary btn-lg btn-block disabled"
                       style="height: 30px; line-height: 10px">You've already commented twice!
                    </a>
                {% else %}
                    <div style="margin-top: 50px; text-align: left" class="form-group">
                    <span class="badge badge-pill badge-light"
                          style="margin-bottom: 10px; font-size: 16px">{{ user.username }}</span>
                        <textarea class="form-control was-validated" id="commentArea" rows="3"
                                  placeholder="Add your comments here..." required></textarea>
                        <span class="invalid-feedback"></span>
                    </div>
                    <button type="button" class="btn btn-outline-primary btn-lg btn-block"
                            style="height: 30px; line-height: 0px" id="btn-comment" onclick="AjaxComment()">Submit your
                        comment
                    </button>
                {% endif %}
            {% else %}
                <div class="card" style="margin-top: 50px">
                    <div class="card-body">
                        <a href="#" data-toggle="modal"
                           data-target="#staticBackdrop" style="cursor: pointer">Log in</a> to comment
                    </div>
                </div>
            {% endif %}
        </div>

        <div style="float:left; margin-left: 10px;">
            <div class="card" style="width: 18rem;">
                <img src="https://steamcdn-a.akamaihd.net/steam/apps/{{ game.appid }}/library_600x900.jpg"
                     class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ game.name }}</h5>
                    <p class="card-text"></p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><a href="https://store.steampowered.com/app/{{ game.appid }}">Steam
                        Store Link</a></li>
                    <li class="list-group-item">Release Date: {{ released }}</li>
                    <li class="list-group-item">{{ developer }}</li>
                    <li class="list-group-item">
                        {% for genre in genres %}
                            {{ genre.name }},
                        {% endfor %}
                    </li>
                </ul>
                {% if user.is_authenticated %}
                    {% if isLike %}
                        <div class="card-body">
                            <a href="#" class="card-link">
                                <button type="button" class="btn btn-outline-danger" id="btn-like"
                                        onclick="AjaxLike()">Dislike..
                                </button>
                            </a>
                            {# <span style="margin-left: 20px" id="likes">{{ game.likes }}</span>#}
                        </div>
                    {% else %}
                        <div class="card-body">
                            <a href="#" class="card-link">
                                <button type="button" class="btn btn-outline-primary" id="btn-like"
                                        onclick="AjaxLike()">Like!
                                </button>
                            </a>
                            {# <span style="margin-left: 20px" id="likes">{{ game.likes }}</span>#}
                        </div>
                    {% endif %}
                {% endif %}
            </div>

            <h5 style="margin-top: 40px">Related News</h5>
            {% for new in news %}
                {% if forloop.counter0 < 5 %}
                    <div class="card" style="max-width: 18rem; margin-top: 20px">
                        <div class="card-body">
                            <a href="{{ new.url }}" target="_blank">
                                <p class="card-text">{{ new.title }}</p>
                            </a>
                            <p class="card-text"><small class="text-muted">Updated
                                on {{ new.date | timeconvert }}</small></p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
            <div style="margin-top: 100px"></div>

        </div>

    </div>

    <script>
        var csrf_token = '{{ csrf_token }}';
        var url_like = {% url 'web:like' %};
        var url_comment = {% url 'web:comment' %};
        var appid = '{{ game.appid }}';
        var user_name = '{{ user.username }}';
    </script>

{% endblock %}

Team_Project/templates/web/index.html
<!DOCTYPE html>
<style>
    .img-thumbnail {
        width: 300px;
        height: 100px;
        margin: 5px;
    }

    .col-sm {
        margin-top: 30px;
    }

</style>
{% extends 'base.html' %}
{% load staticfiles %}
{% load web_template_tags %}

{% block title %}
    Home page
{% endblock %}

{% block content %}

    <div class="embed-responsive embed-responsive-16by9" style="max-width: 960px; text-align: center; margin: 0 auto;">
        {% if video.videoId %}
            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ video.videoId }}?rel=0"
                    allowfullscreen></iframe>
        {% else %}
            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/O2W0N3uKXmo?rel=0"
                    allowfullscreen></iframe>
        {% endif %}
    </div>


    <div class="container-fluid" style="margin-top: 20px;">
        {% for game in five_games %}
            <a href="/game/{{ game.appid }}" target="_blank">
                <img src="https://steamcdn-a.akamaihd.net/steam/apps/{{ game.appid }}/header.jpg"
                     class="img-thumbnail" alt="{{ game.name }}">
            </a>
        {% endfor %}
    </div>

    <div class="container" style="margin-top: 20px; text-align: center; max-width: 1400px; margin: 0 auto;">
        <div class="row" style="margin-bottom: 100px">
            {% for news in games_news %}
                <div class="col-sm">
                    <div class="card" style="width: 18rem;">
                        <a href="/game/{{ news.appid }}" target="_blank">
                            <img src="https://steamcdn-a.akamaihd.net/steam/apps/{{ news.appid }}/header.jpg"
                                 class="card-img-top">
                        </a>
                        <div class="card-body">
                            <a href="{{ news.url }}" target="_blank">
                                <p class="card-text">{{ news.title }}</p>
                            </a>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Updated on {{ news.date|timeconvert }}</small>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    </div>

{% endblock %}

Team_Project/templates/web/search.html
<!DOCTYPE html>
<style>
    .lead {
        float: left;
        margin-left: 30px;
        overflow: hidden;
        text-overflow: ellipsis;
        width: 700px;
        height: 65px;
        display: -webkit-box;
        -webkit-line-clamp: 2;
        -webkit-box-orient: vertical;
    }
    .display-4{
        float: left;
        margin-left: 30px;
        overflow: hidden;
        text-overflow: ellipsis;
        width: 750px;
        height: 75px;
        display: -webkit-box;
        -webkit-line-clamp: 1;
        -webkit-box-orient: vertical;
    }
</style>

{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Results
{% endblock %}

{% block content %}
    {% if search_result %}
        <div class="container" style="width: 80%">
            {% for game in search_result %}
                <div class="jumbotron jumbotron-fluid" style="text-align: left; height: 250px;">
                    <div class="container">
                        <img src="https://steamcdn-a.akamaihd.net/steam/apps/{{ game.0.appid }}/header.jpg"
                             style="float: left; width: 25%" class="img-thumbnail">
                        <a href="/game/{{ game.0.appid }}"><h4 class="display-4"
                                                               style="margin-left: 30px; float: left;">{{ game.0.name }}</h4>
                        </a>
                        <p class="lead">{{ game.1 }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="container-fluid">
            <div class="card bg-dark text-white">
                <img src="https://steamcdn-a.akamaihd.net/steam/apps/570/library_hero.jpg" class="card-img" alt="...">
                <div class="card-img-overlay">
                    <h1 class="card-title">No Matches!</h1>
                    <p class="card-text">Sorry there is nothing you can find in the website.</p>
                    <p class="card-text">Try again!</p>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}